Add missing QRegularExpression include
This fixes the build with Qt 6.9.0-beta2, which otherwise errors out
with
"streamsmodel.cpp:1257:58: error: variable 'constQRegularExpression
brokenXML' has initializer but incomplete type".